version: '3.1'
 services:
  management1:
    image: mysql/mysql-cluster
    volumes:
       - ./file/my.cnf:/my.cnf
       - ./file/mysql-cluster.cnf:/mysql-cluster.cnf
    command: ndb_mgmd
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.2

  node1:
    image: mysql/mysql-cluster
    volumes:
       - ./file/my.cnf:/my.cnf
       - ./file/mysql-cluster.cnf:/mysql-cluster.cnf
    command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.3

  node2:
    image: mysql/mysql-cluster
    volumes:
       - ./file/my.cnf:/my.cnf
       - ./file/mysql-cluster.cnf:/mysql-cluster.cnf
    command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.4

  node3:
    image: mysql/mysql-cluster
    volumes:
       - ./file/my.cnf:/my.cnf
       - ./file/mysql-cluster.cnf:/mysql-cluster.cnf
    command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.5

  mysql1:
    image: mysql/mysql-cluster
    ports:
      - "3906:3906"
    volumes:
       - ./file/my.cnf:/my.cnf
       - ./file/mysql-cluster.cnf:/mysql-cluster.cnf
    environment:
      MYSQL_ROOT_PASSWORD: pucsd
      MYSQL_DATABASE: pucsdStudents
      MYSQL_USER: pucsd
      MYSQL_PASSWORD: pucsd
      MYSQL_ROOT_HOST: '%'
    command: mysqld
    depends_on:
      - "management1"
      - "node1"
      - "node2"
      - "node3"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - mysql1:db
    networks:
      mysqlcluster:

networks:
 mysqlcluster:
  driver: overlay
#  driver: bridge
  ipam:
   config:
    - subnet: 172.28.0.0/16
      gateway: 172.28.5.254
